### ISSUE TITLE
Docs need to be updated for Drone 1.0

### ISSUE THREAD

**Issue by myavorsky** [robertstettner/drone-npm-auth#7]
### Drone configuration example

**Using credentials from secrets**

```
pipeline:
  npm_auth:
    image: robertstettner/drone-npm-auth
    settings:
      registry: "https://your-registry.dev"
      username:
        from_secret: npm_username
      password:
        from_secret: npm_username
      email:
        from_secret: npm_username
```
